M48
; DRILL file KiCad 10.0.3 date 2026-06-23T13:31:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-23T13:31:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.050
%
G90
G05
T1
X222.55Y-74.1
T2
X238.55Y-93.44
X238.55Y-104.14
T3
X215.6Y-53.225
X228.2Y-53.225
M30
