M48
; DRILL file KiCad 10.0.3 date 2026-08-19T09:52:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-19T09:52:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.050
%
G90
G05
T1
X234.95Y-93.85
X234.95Y-104.55
T2
X211.1Y-54.7
X223.7Y-54.7
M30
